import { Artist, Product, User } from "../types";

export const mockUsers: User[] = [
  {
    id: "user1",
    name: "Layla Ibrahim",
    email: "layla@example.com",
    isArtist: true,
    profilePicture: "https://randomuser.me/api/portraits/women/42.jpg",
  },
  {
    id: "user2",
    name: "Omar Nasser",
    email: "omar@example.com",
    isArtist: true,
    profilePicture: "https://randomuser.me/api/portraits/men/36.jpg",
  },
  {
    id: "user3",
    name: "Haya Al-Qasem",
    email: "haya@example.com",
    isArtist: true,
    profilePicture: "https://randomuser.me/api/portraits/women/65.jpg",
  },
  {
    id: "user4",
    name: "Ahmad Khalil",
    email: "ahmad@example.com",
    isArtist: false,
  },
];

export const mockArtists: Artist[] = [
  {
    id: "artist1",
    userId: "user1",
    name: {
      en: "Layla Ibrahim",
      ar: "ليلى إبراهيم",
    },
    bio: {
      en: "Contemporary painter from Amman focusing on abstract expressionism inspired by Jordanian landscapes.",
      ar: "رسامة معاصرة من عمان تركز على التعبيرية التجريدية المستوحاة من المناظر الطبيعية الأردنية.",
    },
    profilePicture: "https://randomuser.me/api/portraits/women/42.jpg",
    coverImage:
      "https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80",
    location: {
      en: "Amman, Jordan",
      ar: "عمان، الأردن",
    },
    socialLinks: {
      instagram: "https://instagram.com/layla",
      facebook: "https://facebook.com/laylart",
      website: "https://laylaibrahim.com",
    },
    tags: ["abstract", "expressionism", "landscape", "contemporary"],
    featured: true,
  },
  {
    id: "artist2",
    userId: "user2",
    name: {
      en: "Omar Nasser",
      ar: "عمر ناصر",
    },
    bio: {
      en: "Calligraphy artist merging traditional Arabic scripts with modern design elements.",
      ar: "فنان خط يدمج بين النصوص العربية التقليدية وعناصر التصميم الحديثة.",
    },
    profilePicture: "https://randomuser.me/api/portraits/men/36.jpg",
    coverImage:
      "https://images.unsplash.com/photo-1581851772610-3eb6a212b9c1?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80",
    location: {
      en: "Amman, Jordan",
      ar: "عمان، الأردن",
    },
    socialLinks: {
      instagram: "https://instagram.com/omarcalligraphy",
      twitter: "https://twitter.com/omarnasser",
    },
    tags: ["calligraphy", "arabic", "typography", "traditional"],
    featured: true,
  },
  {
    id: "artist3",
    userId: "user3",
    name: {
      en: "Haya Al-Qasem",
      ar: "هيا القاسم",
    },
    bio: {
      en: "Ceramic artist creating functional pottery with patterns inspired by Jordanian heritage.",
      ar: "فنانة سيراميك تصنع الفخار الوظيفي بأنماط مستوحاة من التراث الأردني.",
    },
    profilePicture: "https://randomuser.me/api/portraits/women/65.jpg",
    coverImage:
      "https://images.unsplash.com/photo-1565193566173-77a5b2732476?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80",
    location: {
      en: "Zarqa, Jordan",
      ar: "الزرقاء، الأردن",
    },
    socialLinks: {
      instagram: "https://instagram.com/hayapottery",
      facebook: "https://facebook.com/hayacraft",
    },
    tags: ["pottery", "ceramics", "functional", "heritage"],
    featured: false,
  },
];

export const mockProducts: Product[] = [
  {
    id: "product1",
    artistId: "artist1",
    title: {
      en: "Desert Sunset",
      ar: "غروب الصحراء",
    },
    description: {
      en: "Abstract painting capturing the vibrant colors of a Jordanian desert sunset.",
      ar: "لوحة تجريدية تلتقط الألوان النابضة بالحياة لغروب الشمس في الصحراء الأردنية.",
    },
    price: 450,
    currency: "JOD",
    images: [
      "https://images.unsplash.com/photo-1578301978693-85fa9c0320b9?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1552672444-70e8f8687eb0?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80",
    ],
    category: "painting",
    medium: "acrylic",
    dimensions: {
      width: 90,
      height: 60,
      unit: "cm",
    },
    inStock: true,
    featured: true,
    dateCreated: "2023-04-15",
    dateAdded: "2023-05-01",
    tags: ["abstract", "landscape", "sunset", "desert"],
  },
  {
    id: "product2",
    artistId: "artist1",
    title: {
      en: "Petra by Night",
      ar: "البتراء ليلاً",
    },
    description: {
      en: "A moody interpretation of Petra's iconic treasury illuminated by candlelight.",
      ar: "تفسير مزاجي لخزنة البتراء الشهيرة مضاءة بضوء الشموع.",
    },
    price: 600,
    currency: "JOD",
    images: [
      "https://images.unsplash.com/photo-1563779815-a2ef09e3c1e5?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80",
    ],
    category: "painting",
    medium: "oil",
    dimensions: {
      width: 100,
      height: 120,
      unit: "cm",
    },
    inStock: true,
    featured: false,
    dateCreated: "2023-03-10",
    dateAdded: "2023-03-15",
    tags: ["petra", "night", "historical", "atmospheric"],
  },
  {
    id: "product3",
    artistId: "artist2",
    title: {
      en: "Harmony",
      ar: "تناغم",
    },
    description: {
      en: 'Modern calligraphy piece featuring the word "Harmony" in flowing Arabic script.',
      ar: 'قطعة خط حديثة تعرض كلمة "تناغم" بخط عربي منساب.',
    },
    price: 350,
    currency: "JOD",
    images: [
      "https://images.unsplash.com/photo-1599420186946-7b6fb4e297f0?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1600006887935-9f50fb23661a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80",
    ],
    category: "calligraphy",
    medium: "mixed_media",
    dimensions: {
      width: 50,
      height: 70,
      unit: "cm",
    },
    inStock: true,
    featured: true,
    dateCreated: "2023-06-20",
    dateAdded: "2023-06-25",
    tags: ["calligraphy", "arabic", "typography", "harmony"],
  },
  {
    id: "product4",
    artistId: "artist2",
    title: {
      en: "Love Letters",
      ar: "رسائل حب",
    },
    description: {
      en: "A collection of three mini calligraphy pieces featuring love poetry in Arabic.",
      ar: "مجموعة من ثلاث قطع خط صغيرة تضم أشعار الحب بالعربية.",
    },
    price: 275,
    currency: "JOD",
    images: [
      "https://images.unsplash.com/photo-1618828272145-97890b64334a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80",
    ],
    category: "calligraphy",
    medium: "paper",
    dimensions: {
      width: 20,
      height: 30,
      unit: "cm",
    },
    inStock: true,
    featured: false,
    dateCreated: "2023-05-14",
    dateAdded: "2023-05-20",
    tags: ["calligraphy", "arabic", "poetry", "love"],
  },
  {
    id: "product5",
    artistId: "artist3",
    title: {
      en: "Heritage Serving Bowl",
      ar: "وعاء تقديم تراثي",
    },
    description: {
      en: "Handcrafted ceramic bowl with traditional Jordanian patterns in blue and turquoise.",
      ar: "وعاء سيراميك مصنوع يدويًا بأنماط أردنية تقليدية باللونين الأزرق والفيروزي.",
    },
    price: 85,
    currency: "JOD",
    images: [
      "https://images.unsplash.com/photo-1610701596007-11502861dcfa?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1577140149101-0b211b4b896a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80",
    ],
    category: "pottery",
    medium: "ceramic",
    dimensions: {
      width: 25,
      height: 10,
      depth: 25,
      unit: "cm",
    },
    weight: {
      value: 800,
      unit: "g",
    },
    inStock: true,
    quantity: 3,
    featured: true,
    dateCreated: "2023-07-05",
    dateAdded: "2023-07-10",
    tags: ["pottery", "functional", "traditional", "bowl"],
  },
  {
    id: "product6",
    artistId: "artist3",
    title: {
      en: "Desert Bloom Vase",
      ar: "مزهرية ازدهار الصحراء",
    },
    description: {
      en: "Elegant ceramic vase inspired by desert flowers with a gradient glaze from sandy beige to soft pink.",
      ar: "مزهرية سيراميك أنيقة مستوحاة من زهور الصحراء مع طلاء متدرج من البيج الرملي إلى الوردي الناعم.",
    },
    price: 120,
    currency: "JOD",
    images: [
      "https://images.unsplash.com/photo-1578749271270-c8ed14a7b1ce?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80",
    ],
    category: "pottery",
    medium: "ceramic",
    dimensions: {
      width: 15,
      height: 30,
      depth: 15,
      unit: "cm",
    },
    weight: {
      value: 1.2,
      unit: "kg",
    },
    inStock: true,
    quantity: 2,
    featured: false,
    dateCreated: "2023-08-12",
    dateAdded: "2023-08-18",
    tags: ["pottery", "vase", "desert", "floral"],
  },
  {
    id: "product7",
    artistId: "artist3",
    title: {
      en: "Desert Bloom Vase",
      ar: "مزهرية ازدهار الصحراء",
    },
    description: {
      en: "Elegant ceramic vase inspired by desert flowers with a gradient glaze from sandy beige to soft pink.",
      ar: "مزهرية سيراميك أنيقة مستوحاة من زهور الصحراء مع طلاء متدرج من البيج الرملي إلى الوردي الناعم.",
    },
    price: 120,
    currency: "JOD",
    images: [
      "https://images.unsplash.com/photo-1578749271270-c8ed14a7b1ce?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80",
    ],
    category: "pottery",
    medium: "ceramic",
    dimensions: {
      width: 15,
      height: 30,
      depth: 15,
      unit: "cm",
    },
    weight: {
      value: 1.2,
      unit: "kg",
    },
    inStock: true,
    quantity: 2,
    featured: false,
    dateCreated: "2023-08-12",
    dateAdded: "2023-08-18",
    tags: ["pottery", "vase", "desert", "floral"],
  },
  {
    id: "product8",
    artistId: "artist1",
    title: {
      en: "Wadi Rum Mystique",
      ar: "سحر وادي رم",
    },
    description: {
      en: "Abstract landscape capturing the magical rock formations of Wadi Rum at dawn.",
      ar: "منظر تجريدي يلتقط التشكيلات الصخرية الساحرة لوادي رم عند الفجر.",
    },
    price: 550,
    currency: "JOD",
    images: [
      "https://images.unsplash.com/photo-1518632618823-dad29fae4c0e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80",
    ],
    category: "painting",
    medium: "acrylic",
    dimensions: {
      width: 80,
      height: 100,
      unit: "cm",
    },
    inStock: true,
    featured: true,
    dateCreated: "2023-09-05",
    dateAdded: "2023-09-15",
    tags: ["abstract", "landscape", "wadi rum", "dawn"],
  },
  {
    id: "product9",
    artistId: "artist1",
    title: {
      en: "Amman Nights",
      ar: "ليالي عمان",
    },
    description: {
      en: "Vibrant cityscape depicting the glowing lights of Amman's hills at night.",
      ar: "منظر حضاري نابض بالحياة يصور الأضواء المتوهجة لتلال عمان ليلاً.",
    },
    price: 480,
    currency: "JOD",
    images: [
      "https://images.unsplash.com/photo-1564501049412-61c2a3083791?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80",
    ],
    category: "painting",
    medium: "oil",
    dimensions: {
      width: 70,
      height: 90,
      unit: "cm",
    },
    inStock: true,
    featured: false,
    dateCreated: "2023-08-20",
    dateAdded: "2023-09-01",
    tags: ["cityscape", "amman", "night", "urban"],
  },
  {
    id: "product10",
    artistId: "artist2",
    title: {
      en: "Wisdom of Ages",
      ar: "حكمة العصور",
    },
    description: {
      en: "Calligraphic representation of an ancient Arabic proverb about wisdom.",
      ar: "تمثيل خطي لمثل عربي قديم عن الحكمة.",
    },
    price: 320,
    currency: "JOD",
    images: [
      "https://images.unsplash.com/photo-1605100804763-247f67b3557e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80",
    ],
    category: "calligraphy",
    medium: "acrylic",
    dimensions: {
      width: 40,
      height: 60,
      unit: "cm",
    },
    inStock: true,
    featured: true,
    dateCreated: "2023-07-15",
    dateAdded: "2023-07-25",
    tags: ["calligraphy", "arabic", "proverb", "wisdom"],
  },
  {
    id: "product11",
    artistId: "artist2",
    title: {
      en: "Bismillah",
      ar: "بسم الله",
    },
    description: {
      en: "Elegant calligraphic rendition of 'Bismillah' in Diwani script with gold leaf accents.",
      ar: "أداء خطي أنيق لـ 'بسم الله' بخط الديواني مع لمسات من أوراق الذهب.",
    },
    price: 420,
    currency: "JOD",
    images: [
      "https://images.unsplash.com/photo-1605106715994-18d3fecffb98?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80",
    ],
    category: "calligraphy",
    medium: "acrylic",
    dimensions: {
      width: 50,
      height: 70,
      unit: "cm",
    },
    inStock: true,
    featured: true,
    dateCreated: "2023-10-01",
    dateAdded: "2023-10-10",
    tags: ["calligraphy", "arabic", "islamic", "gold"],
  },
  {
    id: "product12",
    artistId: "artist3",
    title: {
      en: "Olive Branch Platter",
      ar: "صحن غصن الزيتون",
    },
    description: {
      en: "Hand-painted ceramic platter featuring olive branch motifs, a symbol of peace in Jordan.",
      ar: "صحن سيراميك مرسوم يدويًا بزخارف أغصان الزيتون، رمز السلام في الأردن.",
    },
    price: 95,
    currency: "JOD",
    images: [
      "https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80",
    ],
    category: "pottery",
    medium: "ceramic",
    dimensions: {
      width: 35,
      height: 35,
      depth: 5,
      unit: "cm",
    },
    weight: {
      value: 1.5,
      unit: "kg",
    },
    inStock: true,
    quantity: 4,
    featured: false,
    dateCreated: "2023-09-18",
    dateAdded: "2023-09-25",
    tags: ["pottery", "olive", "peace", "platter"],
  },
  {
    id: "product13",
    artistId: "artist3",
    title: {
      en: "Bedouin Coffee Set",
      ar: "مجموعة قهوة بدوية",
    },
    description: {
      en: "Traditional Jordanian coffee set with four cups and intricate desert patterns.",
      ar: "مجموعة قهوة أردنية تقليدية بأربعة فنون وأنماط صحراوية معقدة.",
    },
    price: 150,
    currency: "JOD",
    images: [
      "https://images.unsplash.com/photo-1592417817098-8fd3d9eb14a5?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80",
    ],
    category: "pottery",
    medium: "ceramic",
    dimensions: {
      width: 30,
      height: 25,
      depth: 25,
      unit: "cm",
    },
    weight: {
      value: 2,
      unit: "kg",
    },
    inStock: true,
    quantity: 2,
    featured: true,
    dateCreated: "2023-10-05",
    dateAdded: "2023-10-15",
    tags: ["pottery", "coffee", "bedouin", "set"],
  },
  {
    id: "product14",
    artistId: "artist1",
    title: {
      en: "Dead Sea Reflections",
      ar: "انعكاسات البحر الميت",
    },
    description: {
      en: "Abstract interpretation of the mineral-rich waters of the Dead Sea at midday.",
      ar: "تفسير تجريدي للمياه الغنية بالمعادن في البحر الميت عند منتصف النهار.",
    },
    price: 520,
    currency: "JOD",
    images: [
      "https://images.unsplash.com/photo-1562077772-3bd90403f7f0?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80",
    ],
    category: "painting",
    medium: "mixed_media",
    dimensions: {
      width: 90,
      height: 60,
      unit: "cm",
    },
    inStock: true,
    featured: false,
    dateCreated: "2023-11-10",
    dateAdded: "2023-11-20",
    tags: ["abstract", "dead sea", "water", "minerals"],
  },
  {
    id: "product15",
    artistId: "artist2",
    title: {
      en: "Alhamdulillah",
      ar: "الحمد لله",
    },
    description: {
      en: "Modern calligraphy piece featuring 'Alhamdulillah' in Kufic style with geometric patterns.",
      ar: "قطعة خط حديثة تعرض 'الحمد لله' بخط الكوفي مع أنماط هندسية.",
    },
    price: 380,
    currency: "JOD",
    images: [
      "https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80",
    ],
    category: "calligraphy",
    medium: "acrylic",
    dimensions: {
      width: 60,
      height: 80,
      unit: "cm",
    },
    inStock: true,
    featured: true,
    dateCreated: "2023-10-22",
    dateAdded: "2023-11-01",
    tags: ["calligraphy", "arabic", "islamic", "kufic"],
  },
  {
    id: "product16",
    artistId: "artist3",
    title: {
      en: "Mosaic Tea Cups",
      ar: "أكواب شاي فسيفسائية",
    },
    description: {
      en: "Set of six tea cups inspired by ancient Jordanian mosaics with colorful geometric designs.",
      ar: "مجموعة من ستة أكواب شاي مستوحاة من الفسيفساء الأردنية القديمة بتصاميم هندسية ملونة.",
    },
    price: 110,
    currency: "JOD",
    images: [
      "https://images.unsplash.com/photo-1560843581-50fd0d0ee7e1?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80",
    ],
    category: "pottery",
    medium: "ceramic",
    dimensions: {
      width: 8,
      height: 8,
      depth: 8,
      unit: "cm",
    },
    weight: {
      value: 200,
      unit: "g",
    },
    inStock: true,
    quantity: 5,
    featured: false,
    dateCreated: "2023-11-05",
    dateAdded: "2023-11-15",
    tags: ["pottery", "mosaic", "tea", "set"],
  },
  {
    id: "product17",
    artistId: "artist1",
    title: {
      en: "Red Sea Coral",
      ar: "شعاب البحر الأحمر",
    },
    description: {
      en: "Colorful abstract representation of coral reefs in Jordan's Red Sea coast.",
      ar: "تمثيل تجريدي ملون للشعاب المرجانية على ساحل البحر الأحمر الأردني.",
    },
    price: 490,
    currency: "JOD",
    images: [
      "https://images.unsplash.com/photo-1544551763-46a013bb70d5?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80",
    ],
    category: "painting",
    medium: "acrylic",
    dimensions: {
      width: 70,
      height: 100,
      unit: "cm",
    },
    inStock: true,
    featured: false,
    dateCreated: "2023-12-01",
    dateAdded: "2023-12-10",
    tags: ["abstract", "red sea", "coral", "marine"],
  },
  {
    id: "product18",
    artistId: "artist2",
    title: {
      en: "Names of the Prophet",
      ar: "أسماء النبي",
    },
    description: {
      en: "Circular calligraphic composition featuring 99 names of the Prophet Muhammad (PBUH).",
      ar: "تكوين خطي دائري يعرض 99 اسمًا للنبي محمد (صلى الله عليه وسلم).",
    },
    price: 650,
    currency: "JOD",
    images: [
      "https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80",
    ],
    category: "calligraphy",
    medium: "acrylic",
    dimensions: {
      width: 80,
      height: 80,
      unit: "cm",
    },
    inStock: true,
    featured: true,
    dateCreated: "2023-11-20",
    dateAdded: "2023-12-01",
    tags: ["calligraphy", "islamic", "prophet", "gold"],
  },
  {
    id: "product19",
    artistId: "artist3",
    title: {
      en: "Desert Wind Chime",
      ar: "نواسير رياح الصحراء",
    },
    description: {
      en: "Ceramic wind chime with hand-painted desert motifs that create soothing sounds.",
      ar: "نواسير رياح من السيراميك مع زخارف صحراوية مرسومة يدويًا تخلق أصواتًا مهدئة.",
    },
    price: 75,
    currency: "JOD",
    images: [
      "https://images.unsplash.com/photo-1514320291840-2e0a9bf2a9ae?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80",
    ],
    category: "pottery",
    medium: "ceramic",
    dimensions: {
      width: 15,
      height: 40,
      depth: 15,
      unit: "cm",
    },
    weight: {
      value: 1,
      unit: "kg",
    },
    inStock: true,
    quantity: 3,
    featured: false,
    dateCreated: "2023-12-05",
    dateAdded: "2023-12-15",
    tags: ["pottery", "wind chime", "desert", "decorative"],
  },
  {
    id: "product20",
    artistId: "artist1",
    title: {
      en: "Jerash Columns",
      ar: "أعمدة جرش",
    },
    description: {
      en: "Abstract interpretation of the ancient Roman columns in the Jordanian city of Jerash.",
      ar: "تفسير تجريدي للأعمدة الرومانية القديمة في مدينة جرش الأردنية.",
    },
    price: 580,
    currency: "JOD",
    images: [
      "https://images.unsplash.com/photo-1581852057101-85e7e9a6b9c1?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80",
    ],
    category: "painting",
    medium: "oil",
    dimensions: {
      width: 100,
      height: 150,
      unit: "cm",
    },
    inStock: true,
    featured: true,
    dateCreated: "2024-01-10",
    dateAdded: "2024-01-20",
    tags: ["abstract", "jerash", "columns", "historical"],
  },
  {
    id: "product21",
    artistId: "artist2",
    title: {
      en: "Allah and Muhammad",
      ar: "الله ومحمد",
    },
    description: {
      en: "Classic calligraphic composition pairing the names of Allah and the Prophet Muhammad (PBUH).",
      ar: "تكوين خطي كلاسيكي يجمع بين اسمي الله والنبي محمد (صلى الله عليه وسلم).",
    },
    price: 500,
    currency: "JOD",
    images: [
      "https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80",
    ],
    category: "calligraphy",
    medium: "acrylic",
    dimensions: {
      width: 50,
      height: 70,
      unit: "cm",
    },
    inStock: true,
    featured: true,
    dateCreated: "2024-01-15",
    dateAdded: "2024-01-25",
    tags: ["calligraphy", "islamic", "allah", "prophet"],
  },
  {
    id: "product22",
    artistId: "artist3",
    title: {
      en: "Dibeen Forest Mug",
      ar: "كوب غابة دبين",
    },
    description: {
      en: "Handcrafted ceramic mug with pine tree motifs inspired by Jordan's Dibeen Forest.",
      ar: "كوب سيراميك مصنوع يدويًا بزخارف أشجار الصنوبر المستوحاة من غابة دبين الأردنية.",
    },
    price: 45,
    currency: "JOD",
    images: [
      "https://images.unsplash.com/photo-1571902943202-507ec2618e8f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80",
    ],
    category: "pottery",
    medium: "ceramic",
    dimensions: {
      width: 10,
      height: 12,
      depth: 10,
      unit: "cm",
    },
    weight: {
      value: 350,
      unit: "g",
    },
    inStock: true,
    quantity: 6,
    featured: false,
    dateCreated: "2024-02-01",
    dateAdded: "2024-02-10",
    tags: ["pottery", "mug", "forest", "nature"],
  },
  {
    id: "product23",
    artistId: "artist1",
    title: {
      en: "Dana Biosphere",
      ar: "محمية ضانا",
    },
    description: {
      en: "Abstract landscape inspired by the colors and textures of Jordan's Dana Biosphere Reserve.",
      ar: "منظر طبيعي تجريدي مستوحى من ألوان وملمس محمية ضانا للأحياء البرية في الأردن.",
    },
    price: 530,
    currency: "JOD",
    images: [
      "https://images.unsplash.com/photo-1465146344425-f00d5f5c8f07?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80",
    ],
    category: "painting",
    medium: "mixed_media",
    dimensions: {
      width: 80,
      height: 120,
      unit: "cm",
    },
    inStock: true,
    featured: false,
    dateCreated: "2024-02-15",
    dateAdded: "2024-02-25",
    tags: ["abstract", "dana", "biosphere", "nature"],
  },
  {
    id: "product24",
    artistId: "artist2",
    title: {
      en: "Ayat al-Kursi",
      ar: "آية الكرسي",
    },
    description: {
      en: "Elegant calligraphy of the Throne Verse (Ayat al-Kursi) in gold and blue.",
      ar: "خط أنيق لآية الكرسي باللونين الذهبي والأزرق.",
    },
    price: 750,
    currency: "JOD",
    images: [
      "https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80",
    ],
    category: "calligraphy",
    medium: "acrylic",
    dimensions: {
      width: 60,
      height: 90,
      unit: "cm",
    },
    inStock: true,
    featured: true,
    dateCreated: "2024-03-01",
    dateAdded: "2024-03-10",
    tags: ["calligraphy", "islamic", "quran", "gold"],
  },
  {
    id: "product25",
    artistId: "artist3",
    title: {
      en: "Seven Sleepers Plate",
      ar: "صحن أهل الكهف",
    },
    description: {
      en: "Decorative plate featuring motifs inspired by the Cave of the Seven Sleepers near Amman.",
      ar: "صحن زخرفي بزخارف مستوحاة من كهف أهل الكهف بالقرب من عمان.",
    },
    price: 90,
    currency: "JOD",
    images: [
      "https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80",
    ],
    category: "pottery",
    medium: "ceramic",
    dimensions: {
      width: 25,
      height: 25,
      depth: 5,
      unit: "cm",
    },
    weight: {
      value: 800,
      unit: "g",
    },
    inStock: true,
    quantity: 3,
    featured: false,
    dateCreated: "2024-03-15",
    dateAdded: "2024-03-25",
    tags: ["pottery", "plate", "historical", "decorative"],
  },
  {
    id: "product26",
    artistId: "artist1",
    title: {
      en: "Mujib Canyon",
      ar: "وادي الموجب",
    },
    description: {
      en: "Dramatic abstract representation of the Mujib Biosphere Reserve's canyon walls.",
      ar: "تمثيل تجريدي درامي لجدران وادي الموجب في المحمية الطبيعية.",
    },
    price: 620,
    currency: "JOD",
    images: [
      "https://images.unsplash.com/photo-1465146344425-f00d5f5c8f07?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80",
    ],
    category: "painting",
    medium: "acrylic",
    dimensions: {
      width: 100,
      height: 150,
      unit: "cm",
    },
    inStock: true,
    featured: true,
    dateCreated: "2024-04-01",
    dateAdded: "2024-04-10",
    tags: ["abstract", "mujib", "canyon", "nature"],
  },
  {
    id: "product27",
    artistId: "artist2",
    title: {
      en: "Surah Al-Ikhlas",
      ar: "سورة الإخلاص",
    },
    description: {
      en: "Beautiful calligraphic rendition of Surah Al-Ikhlas in Thuluth script.",
      ar: "أداء خطي جميل لسورة الإخلاص بخط الثلث.",
    },
    price: 400,
    currency: "JOD",
    images: [
      "https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80",
    ],
    category: "calligraphy",
    medium: "acrylic",
    dimensions: {
      width: 50,
      height: 70,
      unit: "cm",
    },
    inStock: true,
    featured: false,
    dateCreated: "2024-04-05",
    dateAdded: "2024-04-15",
    tags: ["calligraphy", "islamic", "quran", "thuluth"],
  },
];
